#!/bin/sh
echo -e "\e[1;32m==>\e[0m Downloading x86_64 version"
curl -fLC -  --retry 3 --retry-delay 3 -o google-chrome-unstable_current_x86_64.rpm "https://dl.google.com/linux/direct/google-chrome-unstable_current_x86_64.rpm"
echo -e "\e[1;32m==>\e[0mi Downloading i386 version"
curl -fLC -  --retry 3 --retry-delay 3 -o google-chrome-unstable_current_i386.rpm "https://dl.google.com/linux/direct/google-chrome-unstable_current_i386.rpm"
echo -e "\e[1;32m==>\e[0m Generating checksums"
echo | sha512sum *.rpm
echo -e "\e[1;32m==>\e[0m Checking license for changes"
lynx --dump "https://www.google.com/chrome/intl/en/eula_text.html" > LICENSE
new=$(sha512sum LICENSE)
if [ "${new}" == "2d09d2ca3c960f38463ed742a2f038e919363fe2cb8d65d86cd4672559b44369037d94f9a09ede478fadd20b4a6dc9271e8d1af1f2cc2bc92ed90d0a4810ac67  LICENSE" ]; then
    echo "license unchanged"
else
    echo "license changed"
    echo ${new}
fi
echo -e "\e[1;32m==>\e[0m Done"
