#!/bin/sh
echo -e "\e[1;32m==>\e[0m Building package"
makepkg
echo -e "\e[1;32m==>\e[0m Building source package"
makepkg --source
echo -e "\e[1;32m==>\e[0m Displaying package contents"
tar -tvf *.pkg.tar.xz
echo -e "\e[1;32m==>\e[0m Running namcap on PKGBUILD"
namcap PKGBUILD
echo -e "\e[1;32m==>\e[0m Running namcap on built package"
namcap *.pkg.tar.xz
echo -e "\e[1;32m==>\e[0m Done"
