#!/bin/sh
echo -e "\e[1;32m==>\e[1;37m Updating checksums"
updpkgsums
echo -e "\e[1;32m==>\e[1;37m Building package"
makepkg -i
echo -e "\e[1;32m==>\e[1;37m Removing built package"
rm -v *.xz
echo -e "\e[1;32m==>\e[1;37m Done"
